import React from "react";
import { View, Text, TouchableOpacity } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { User, MapCoordinate } from "@/services/mockData";
import { buildMapHtml, MapMarker } from "./mapHtml";
import { useThemeColors } from "@/services/theme";

interface InteractiveMapProps {
  mapItems: MapCoordinate[];
  currentUser: User | null;
  userLocation: { latitude: number; longitude: number } | null;
  onRefreshMap: () => void;
}

/**
 * Web implementation: the Leaflet document is rendered into a sandboxed
 * iframe. See InteractiveMap.native.tsx for the react-native-webview
 * counterpart — both share buildMapHtml() so the map looks identical.
 */
export default function InteractiveMap({
  mapItems,
  currentUser,
  userLocation,
  onRefreshMap,
}: InteractiveMapProps) {
  const c = useThemeColors();
  const markers: MapMarker[] = mapItems.map((item) => ({
    ...item,
    relation: currentUser && item.userId === currentUser.id ? "self" : "friend",
  }));

  const html = buildMapHtml(markers, userLocation);

  return (
    <View className="flex-1 bg-bg border border-line rounded-3xl overflow-hidden relative min-h-[450px]">
      {React.createElement("iframe", {
        srcDoc: html,
        style: { width: "100%", height: "100%", border: "none", minHeight: 450 },
        title: "TrinkDuell Karte",
        // Leaflet needs same-origin to initialise; with allow-scripts alone
        // the map stays blank. The document is generated by us and all
        // user-supplied strings are HTML-escaped in buildMapHtml(), so it
        // isn't rendering untrusted markup.
        sandbox: "allow-scripts allow-same-origin",
      })}

      <TouchableOpacity
        onPress={onRefreshMap}
        activeOpacity={0.8}
        className="absolute top-4 left-4 bg-surface/90 border border-line p-2 rounded-xl flex-row items-center active:scale-95"
      >
        <Ionicons name="refresh" size={14} color={c.accent} />
        <Text className="text-[8px] text-accent-ink font-black uppercase tracking-widest ml-1.5">
          Aktualisieren
        </Text>
      </TouchableOpacity>

      {mapItems.length === 0 && (
        <View className="absolute bottom-4 left-4 right-4 bg-surface/90 border border-line rounded-2xl p-3 pointer-events-none">
          <Text className="text-content text-[10px] font-black uppercase tracking-wider mb-0.5">
            Noch keine Orte
          </Text>
          <Text className="text-content-faint text-[9px] font-semibold leading-relaxed">
            Aktiviere den Standort unter Menü → Einstellungen, um deine Getränke-Orte hier zu sehen.
          </Text>
        </View>
      )}
    </View>
  );
}
